In [1]:
import polars as pl
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

Matplotlib is building the font cache; this may take a moment.

_Captains log, stardate 2026-09-07 0745_

**Captain Max** has taken command of the ship *Unsinkable 2*.

In [35]:
print("power up submarine")

power up submarine

_Captains log, stardate 2026-09-07 0750_

## Read and Write Data

1. write the data to a CSV file
df...

2. read the CSV file to a new DataFrame
...

3. write the data to an Excel file
...

4. read the Excel file to a new DataFrame
...

5. write the data to a JSON file
...

6. read the JSON file to a new DataFrame
...

7. check the rows and columns of one DataFrame.
df.shape

In [36]:
import polars as pl
df = pl.read_csv('data/panda_sector.csv', separator=',', has_header=True)

In [37]:
print(df)

shape: (306, 4)
┌────────┬────────┬─────────────┬──────┐
│ x      ┆ y      ┆ type        ┆ size │
│ ---    ┆ ---    ┆ ---         ┆ ---  │
│ f64    ┆ f64    ┆ str         ┆ i64  │
╞════════╪════════╪═════════════╪══════╡
│ 255.08 ┆ 271.65 ┆ ice_hole    ┆ 7    │
│ 268.66 ┆ 248.81 ┆ ice_hole    ┆ 8    │
│ 250.18 ┆ 232.47 ┆ abyss       ┆ 19   │
│ 212.59 ┆ 241.67 ┆ kelp_forest ┆ 16   │
│ 262.01 ┆ 227.38 ┆ corals      ┆ 7    │
│ …      ┆ …      ┆ …           ┆ …    │
│ 336.04 ┆ 274.84 ┆ abyss       ┆ 1    │
│ 209.1  ┆ 248.77 ┆ rocks       ┆ 17   │
│ 283.63 ┆ 273.58 ┆ danger      ┆ 5    │
│ 187.42 ┆ 254.14 ┆ rocks       ┆ 2    │
│ 338.72 ┆ 235.52 ┆ corals      ┆ 9    │
└────────┴────────┴─────────────┴──────┘

In [38]:
print(df.shape)

(306, 4)

In [39]:
import polars as pl
df = pl.read_excel('data/penguin_sector.xlsx', engine='calamine')

/var/folders/5_/0wmfbw9s5y34jq82848gv2qw0000gn/T/ipykernel_62966/2882069132.py:2: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df = pl.read_excel('data/penguin_sector.xlsx', engine='calamine')

In [40]:
print(df)

shape: (306, 4)
┌────────┬────────┬────────────────┬──────┐
│ x      ┆ y      ┆ type           ┆ size │
│ ---    ┆ ---    ┆ ---            ┆ ---  │
│ f64    ┆ f64    ┆ str            ┆ i64  │
╞════════╪════════╪════════════════╪══════╡
│ 204.19 ┆ 257.22 ┆ rocks          ┆ 4    │
│ 330.18 ┆ 237.82 ┆ strong_current ┆ 17   │
│ 139.74 ┆ 259.37 ┆ strong_current ┆ 17   │
│ 328.98 ┆ 233.14 ┆ fishing_ground ┆ 18   │
│ 179.14 ┆ 270.31 ┆ strong_current ┆ 16   │
│ …      ┆ …      ┆ …              ┆ …    │
│ 120.05 ┆ 295.98 ┆ abyss          ┆ 4    │
│ 368.43 ┆ 209.63 ┆ kelp_forest    ┆ 6    │
│ 128.45 ┆ 284.17 ┆ island         ┆ 1    │
│ 385.72 ┆ 202.29 ┆ kelp_forest    ┆ 4    │
│ 109.36 ┆ 291.97 ┆ rocks          ┆ 11   │
└────────┴────────┴────────────────┴──────┘

In [41]:
df = pl.read_json('data/amoeba_sector.json')

In [42]:
print(df)

shape: (306, 4)
┌────────┬────────┬────────────────┬──────┐
│ x      ┆ y      ┆ type           ┆ size │
│ ---    ┆ ---    ┆ ---            ┆ ---  │
│ f64    ┆ f64    ┆ str            ┆ i64  │
╞════════╪════════╪════════════════╪══════╡
│ 377.86 ┆ 219.31 ┆ kelp_forest    ┆ 12   │
│ 123.09 ┆ 281.48 ┆ corals         ┆ 5    │
│ 381.44 ┆ 209.9  ┆ island         ┆ 16   │
│ 121.68 ┆ 274.16 ┆ strong_current ┆ 13   │
│ 376.4  ┆ 222.38 ┆ abyss          ┆ 13   │
│ …      ┆ …      ┆ …              ┆ …    │
│ 424.19 ┆ 160.03 ┆ rocks          ┆ 15   │
│ 71.66  ┆ 330.94 ┆ island         ┆ 1    │
│ 431.29 ┆ 166.91 ┆ kelp_forest    ┆ 7    │
│ 64.9   ┆ 331.07 ┆ kelp_forest    ┆ 12   │
│ 428.26 ┆ 166.53 ┆ rocks          ┆ 10   │
└────────┴────────┴────────────────┴──────┘

In [43]:
import polars as pl
df1 = pl.read_csv('data/panda_sector.csv', separator=',', has_header=True)
df2 = pl.read_excel('data/penguin_sector.xlsx', engine='calamine')
df3 = pl.read_json('data/amoeba_sector.json')
df = pl.concat([df1, df2, df3])

/var/folders/5_/0wmfbw9s5y34jq82848gv2qw0000gn/T/ipykernel_62966/4247259677.py:3: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df2 = pl.read_excel('data/penguin_sector.xlsx', engine='calamine')

In [44]:
df.write_csv('data/deep_sea.csv')

In [45]:
df = pl.read_csv('data/penguin_sector.csv')

In [46]:
df.write_csv('data/new_csv.csv')

In [47]:
import polars as pl
df2 = pl.read_csv('data/new_csv.csv')

In [48]:
df2.write_excel('data/new_excel.xlsx')

In [49]:
df3 = pl.read_excel('data/new_excel.xlsx', engine='calamine')

/var/folders/5_/0wmfbw9s5y34jq82848gv2qw0000gn/T/ipykernel_62966/4076187283.py:1: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df3 = pl.read_excel('data/new_excel.xlsx', engine='calamine')

In [50]:
df3.write_json('data/new_json.json')

In [51]:
df4 = pl.read_json('data/new_json.json')

In [52]:
df4.shape

(306, 4)

_Captains log, stardate 2026-09-07 1655_

## Inspect DataFrames

Inspect the report stations.csv. Solve the following tasks

display the number of rows and columns

display the last 5 rows

list the column names

how many stations does the ship have?

how many different security levels are there?

which of the stations is under construction?

where did Ming Ming, the intern, go?

In [53]:
import polars as pl
df = pl.read_csv('data/stations.csv')

In [54]:
df.head(2)

shape: (2, 4)
┌─────────┬────────┬───────┬──────────┐
│ station ┆ status ┆ bears ┆ security │
│ ---     ┆ ---    ┆ ---   ┆ ---      │
│ str     ┆ str    ┆ i64   ┆ str      │
╞═════════╪════════╪═══════╪══════════╡
│ bridge  ┆ OK     ┆ 1     ┆ red      │
│ reactor ┆ OK     ┆ 0     ┆ red      │
└─────────┴────────┴───────┴──────────┘

In [55]:
df.shape

(18, 4)

In [56]:
df.dtypes

[String, String, Int64, String]

In [57]:
df

shape: (18, 4)
┌──────────────────┬────────┬───────┬──────────┐
│ station          ┆ status ┆ bears ┆ security │
│ ---              ┆ ---    ┆ ---   ┆ ---      │
│ str              ┆ str    ┆ i64   ┆ str      │
╞══════════════════╪════════╪═══════╪══════════╡
│ bridge           ┆ OK     ┆ 1     ┆ red      │
│ reactor          ┆ OK     ┆ 0     ┆ red      │
│ engines          ┆ OK     ┆ 0     ┆ red      │
│ shuttle bay      ┆ OK     ┆ 0     ┆ blue     │
│ mess             ┆ OK     ┆ 0     ┆ green    │
│ …                ┆ …      ┆ …     ┆ …        │
│ main hatch       ┆ OK     ┆ 0     ┆ blue     │
│ floatation tanks ┆ OK     ┆ 0     ┆ orange   │
│ scuba bay        ┆ OK     ┆ 0     ┆ orange   │
│ bar              ┆ OK     ┆ 0     ┆ green    │
│ computer core    ┆ OK     ┆ 0     ┆ red      │
└──────────────────┴────────┴───────┴──────────┘

In [58]:
df.glimpse()

Rows: 18
Columns: 4
$ station  <str> 'bridge', 'reactor', 'engines', 'shuttle bay', 'mess', 'galley', 'sauna', 'quarters', 'cargo bay', 'cold storage'
$ status   <str> 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'under construction', 'OK', 'OK', 'OK'
$ bears    <i64> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ security <str> 'red', 'red', 'red', 'blue', 'green', 'blue', 'green', 'green', 'blue', 'blue'

In [59]:
df['security'].value_counts()

shape: (4, 2)
┌──────────┬───────┐
│ security ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ blue     ┆ 6     │
│ orange   ┆ 3     │
│ green    ┆ 5     │
│ red      ┆ 4     │
└──────────┴───────┘

In [60]:
df['security'].unique()

shape: (4,)
Series: 'security' [str]
[
	"orange"
	"red"
	"green"
	"blue"
]

In [61]:
df.shape

(18, 4)

In [62]:
df.tail(5)

shape: (5, 4)
┌──────────────────┬────────┬───────┬──────────┐
│ station          ┆ status ┆ bears ┆ security │
│ ---              ┆ ---    ┆ ---   ┆ ---      │
│ str              ┆ str    ┆ i64   ┆ str      │
╞══════════════════╪════════╪═══════╪══════════╡
│ main hatch       ┆ OK     ┆ 0     ┆ blue     │
│ floatation tanks ┆ OK     ┆ 0     ┆ orange   │
│ scuba bay        ┆ OK     ┆ 0     ┆ orange   │
│ bar              ┆ OK     ┆ 0     ┆ green    │
│ computer core    ┆ OK     ┆ 0     ┆ red      │
└──────────────────┴────────┴───────┴──────────┘

In [63]:
df.glimpse()

Rows: 18
Columns: 4
$ station  <str> 'bridge', 'reactor', 'engines', 'shuttle bay', 'mess', 'galley', 'sauna', 'quarters', 'cargo bay', 'cold storage'
$ status   <str> 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'under construction', 'OK', 'OK', 'OK'
$ bears    <i64> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ security <str> 'red', 'red', 'red', 'blue', 'green', 'blue', 'green', 'green', 'blue', 'blue'

In [64]:
df[0]

shape: (1, 4)
┌─────────┬────────┬───────┬──────────┐
│ station ┆ status ┆ bears ┆ security │
│ ---     ┆ ---    ┆ ---   ┆ ---      │
│ str     ┆ str    ┆ i64   ┆ str      │
╞═════════╪════════╪═══════╪══════════╡
│ bridge  ┆ OK     ┆ 1     ┆ red      │
└─────────┴────────┴───────┴──────────┘

In [65]:
df.schema

Schema([('station', String),
        ('status', String),
        ('bears', Int64),
        ('security', String)])

In [66]:
df.height

18

In [67]:
df['security'].unique()

shape: (4,)
Series: 'security' [str]
[
	"blue"
	"red"
	"green"
	"orange"
]

In [68]:
df.glimpse('status' == 'under construction')

TypeError: DataFrame.glimpse() takes 1 positional argument but 2 were given

In [ ]:
import polars as pl
df.filter(pl.col('status') == 'under construction')

shape: (1, 4)
┌─────────┬────────────────────┬───────┬──────────┐
│ station ┆ status             ┆ bears ┆ security │
│ ---     ┆ ---                ┆ ---   ┆ ---      │
│ str     ┆ str                ┆ i64   ┆ str      │
╞═════════╪════════════════════╪═══════╪══════════╡
│ sauna   ┆ under construction ┆ 0     ┆ green    │
└─────────┴────────────────────┴───────┴──────────┘

In [ ]:
df.glimpse()

Rows: 18
Columns: 4
$ station  <str> 'bridge', 'reactor', 'engines', 'shuttle bay', 'mess', 'galley', 'sauna', 'quarters', 'cargo bay', 'cold storage'
$ status   <str> 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'under construction', 'OK', 'OK', 'OK'
$ bears    <i64> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ security <str> 'red', 'red', 'red', 'blue', 'green', 'blue', 'green', 'green', 'blue', 'blue'

In [ ]:
df.filter(pl.col('bears') > 0)

shape: (2, 4)
┌────────────┬────────┬───────┬──────────┐
│ station    ┆ status ┆ bears ┆ security │
│ ---        ┆ ---    ┆ ---   ┆ ---      │
│ str        ┆ str    ┆ i64   ┆ str      │
╞════════════╪════════╪═══════╪══════════╡
│ bridge     ┆ OK     ┆ 1     ┆ red      │
│ navigation ┆ OK     ┆ 1     ┆ green    │
└────────────┴────────┴───────┴──────────┘

_2026-09-07 1703_

## Select Rows and Columns

Select rows from the bar registry bar.csv to find your five crew members. You have a couple of hints:

Lumi (the helmsman) is easily recognizable by his red headscarf.

Ilmar (the ships carpenter) has at exactly 24 tattoos and a headscarf that is blue or indigo.

Andromé (navigator) has a green headscarf and more earrings than Boreaboy.

Boreaboy (cook) has exactly between 8 and 11 earrings and less than 5 tattoos. He has no headscarf.

Ming Ming, the intern from the remote planet of Pandalor has no tattoos, earrings or scarf

Identify all five of them by their id.

In [4]:
import polars as pl
df = pl.read_csv('data/bar.csv')

In [70]:
df.columns

['id', 'headscarf', 'earrings', 'tattoos']

In [71]:
df['id']

shape: (100,)
Series: 'id' [i64]
[
	0
	1
	2
	3
	4
	…
	95
	96
	97
	98
	99
]

In [73]:
df[['id', 'headscarf']]

shape: (100, 2)
┌─────┬───────────┐
│ id  ┆ headscarf │
│ --- ┆ ---       │
│ i64 ┆ str       │
╞═════╪═══════════╡
│ 0   ┆ indigo    │
│ 1   ┆ green     │
│ 2   ┆ indigo    │
│ 3   ┆ pink      │
│ 4   ┆ null      │
│ …   ┆ …         │
│ 95  ┆ black     │
│ 96  ┆ black     │
│ 97  ┆ indigo    │
│ 98  ┆ black     │
│ 99  ┆ null      │
└─────┴───────────┘

In [75]:
df.slice(8, 29)

shape: (29, 4)
┌─────┬───────────┬──────────┬─────────┐
│ id  ┆ headscarf ┆ earrings ┆ tattoos │
│ --- ┆ ---       ┆ ---      ┆ ---     │
│ i64 ┆ str       ┆ i64      ┆ i64     │
╞═════╪═══════════╪══════════╪═════════╡
│ 8   ┆ indigo    ┆ 2        ┆ 1       │
│ 9   ┆ pink      ┆ 0        ┆ 2       │
│ 10  ┆ pink      ┆ 10       ┆ 16      │
│ 11  ┆ null      ┆ 4        ┆ 4       │
│ 12  ┆ blue      ┆ 9        ┆ 16      │
│ …   ┆ …         ┆ …        ┆ …       │
│ 32  ┆ blue      ┆ 2        ┆ 23      │
│ 33  ┆ null      ┆ 0        ┆ 16      │
│ 34  ┆ indigo    ┆ 2        ┆ 5       │
│ 35  ┆ indigo    ┆ 4        ┆ 23      │
│ 36  ┆ blue      ┆ 2        ┆ 4       │
└─────┴───────────┴──────────┴─────────┘

In [77]:
df.slice(2,8).select(df.columns[2:4])

shape: (8, 2)
┌──────────┬─────────┐
│ earrings ┆ tattoos │
│ ---      ┆ ---     │
│ i64      ┆ i64     │
╞══════════╪═════════╡
│ 7        ┆ 19      │
│ 10       ┆ 16      │
│ 2        ┆ 16      │
│ 0        ┆ 19      │
│ 7        ┆ 11      │
│ 2        ┆ 6       │
│ 2        ┆ 1       │
│ 0        ┆ 2       │
└──────────┴─────────┘

In [78]:
df[2:8, 2:4]

shape: (6, 2)
┌──────────┬─────────┐
│ earrings ┆ tattoos │
│ ---      ┆ ---     │
│ i64      ┆ i64     │
╞══════════╪═════════╡
│ 7        ┆ 19      │
│ 10       ┆ 16      │
│ 2        ┆ 16      │
│ 0        ┆ 19      │
│ 7        ┆ 11      │
│ 2        ┆ 6       │
└──────────┴─────────┘

In [79]:
df.filter(pl.col('earrings') == 0)

shape: (10, 4)
┌─────┬───────────┬──────────┬─────────┐
│ id  ┆ headscarf ┆ earrings ┆ tattoos │
│ --- ┆ ---       ┆ ---      ┆ ---     │
│ i64 ┆ str       ┆ i64      ┆ i64     │
╞═════╪═══════════╪══════════╪═════════╡
│ 5   ┆ green     ┆ 0        ┆ 19      │
│ 9   ┆ pink      ┆ 0        ┆ 2       │
│ 22  ┆ white     ┆ 0        ┆ 0       │
│ 33  ┆ null      ┆ 0        ┆ 16      │
│ 37  ┆ pink      ┆ 0        ┆ 19      │
│ 49  ┆ white     ┆ 0        ┆ 19      │
│ 78  ┆ null      ┆ 0        ┆ 0       │
│ 79  ┆ orange    ┆ 0        ┆ 15      │
│ 92  ┆ green     ┆ 0        ┆ 23      │
│ 99  ┆ null      ┆ 0        ┆ 16      │
└─────┴───────────┴──────────┴─────────┘

In [81]:
df.filter((pl.col('earrings') > 1) & (pl.col('earrings') < 4))

shape: (16, 4)
┌─────┬───────────┬──────────┬─────────┐
│ id  ┆ headscarf ┆ earrings ┆ tattoos │
│ --- ┆ ---       ┆ ---      ┆ ---     │
│ i64 ┆ str       ┆ i64      ┆ i64     │
╞═════╪═══════════╪══════════╪═════════╡
│ 4   ┆ null      ┆ 2        ┆ 16      │
│ 7   ┆ pink      ┆ 2        ┆ 6       │
│ 8   ┆ indigo    ┆ 2        ┆ 1       │
│ 27  ┆ blue      ┆ 2        ┆ 5       │
│ 32  ┆ blue      ┆ 2        ┆ 23      │
│ …   ┆ …         ┆ …        ┆ …       │
│ 59  ┆ black     ┆ 2        ┆ 7       │
│ 71  ┆ white     ┆ 3        ┆ 6       │
│ 83  ┆ null      ┆ 3        ┆ 22      │
│ 85  ┆ white     ┆ 2        ┆ 8       │
│ 93  ┆ indigo    ┆ 2        ┆ 21      │
└─────┴───────────┴──────────┴─────────┘

In [82]:
df.sample(11)

shape: (11, 4)
┌─────┬───────────┬──────────┬─────────┐
│ id  ┆ headscarf ┆ earrings ┆ tattoos │
│ --- ┆ ---       ┆ ---      ┆ ---     │
│ i64 ┆ str       ┆ i64      ┆ i64     │
╞═════╪═══════════╪══════════╪═════════╡
│ 13  ┆ null      ┆ 6        ┆ 23      │
│ 35  ┆ indigo    ┆ 4        ┆ 23      │
│ 46  ┆ orange    ┆ 11       ┆ 5       │
│ 75  ┆ indigo    ┆ 11       ┆ 19      │
│ 62  ┆ blue      ┆ 1        ┆ 7       │
│ …   ┆ …         ┆ …        ┆ …       │
│ 33  ┆ null      ┆ 0        ┆ 16      │
│ 37  ┆ pink      ┆ 0        ┆ 19      │
│ 84  ┆ green     ┆ 8        ┆ 8       │
│ 43  ┆ white     ┆ 8        ┆ 15      │
│ 53  ┆ indigo    ┆ 6        ┆ 18      │
└─────┴───────────┴──────────┴─────────┘

In [ ]:
lumi = df.filter(pl.col('headscarf') == 'red')
print("Lumi is:")
print(lumi)
sum_ids = lumi['id'][0]

Lumi is:
shape: (1, 4)
┌─────┬───────────┬──────────┬─────────┐
│ id  ┆ headscarf ┆ earrings ┆ tattoos │
│ --- ┆ ---       ┆ ---      ┆ ---     │
│ i64 ┆ str       ┆ i64      ┆ i64     │
╞═════╪═══════════╪══════════╪═════════╡
│ 29  ┆ red       ┆ 7        ┆ 3       │
└─────┴───────────┴──────────┴─────────┘
29

In [35]:
ilmar = df.filter((pl.col('tattoos') == 24) &
                  (pl.col('headscarf').is_in(['blue', 'indigo'])))
print("Ilmar is: ")
print(ilmar)
sum_ids += ilmar['id'][0]

Ilmar is:
shape: (1, 4)
┌─────┬───────────┬──────────┬─────────┐
│ id  ┆ headscarf ┆ earrings ┆ tattoos │
│ --- ┆ ---       ┆ ---      ┆ ---     │
│ i64 ┆ str       ┆ i64      ┆ i64     │
╞═════╪═══════════╪══════════╪═════════╡
│ 66  ┆ blue      ┆ 5        ┆ 24      │
└─────┴───────────┴──────────┴─────────┘

In [36]:
androme = df.filter((pl.col('headscarf') == 'green') &
                    (pl.col('earrings') > 10)) #update once Boreaboy was found
print("Andromé is: ")
print(androme)
sum_ids += androme['id'][0]

Andromé is:
shape: (1, 4)
┌─────┬───────────┬──────────┬─────────┐
│ id  ┆ headscarf ┆ earrings ┆ tattoos │
│ --- ┆ ---       ┆ ---      ┆ ---     │
│ i64 ┆ str       ┆ i64      ┆ i64     │
╞═════╪═══════════╪══════════╪═════════╡
│ 67  ┆ green     ┆ 11       ┆ 17      │
└─────┴───────────┴──────────┴─────────┘

In [37]:
boreaboy = df.filter((pl.col('earrings').is_between(7,12)) &
                     (pl.col('tattoos') < 5) &
                     (pl.col('headscarf').is_null()))
print("Boreaboy is: ")
print(boreaboy)
sum_ids += boreaboy['id'][0]

Boreaboy is:
shape: (1, 4)
┌─────┬───────────┬──────────┬─────────┐
│ id  ┆ headscarf ┆ earrings ┆ tattoos │
│ --- ┆ ---       ┆ ---      ┆ ---     │
│ i64 ┆ str       ┆ i64      ┆ i64     │
╞═════╪═══════════╪══════════╪═════════╡
│ 81  ┆ null      ┆ 10       ┆ 4       │
└─────┴───────────┴──────────┴─────────┘

In [38]:
ming_ming = df.filter((pl.col('tattoos') == 0) &
                      (pl.col('earrings') == 0) &
                      (pl.col('headscarf').is_null()))
print("Ming Ming is: ")
print(ming_ming)
sum_ids += ming_ming['id'][0]

Ming Ming is:
shape: (1, 4)
┌─────┬───────────┬──────────┬─────────┐
│ id  ┆ headscarf ┆ earrings ┆ tattoos │
│ --- ┆ ---       ┆ ---      ┆ ---     │
│ i64 ┆ str       ┆ i64      ┆ i64     │
╞═════╪═══════════╪══════════╪═════════╡
│ 78  ┆ null      ┆ 0        ┆ 0       │
└─────┴───────────┴──────────┴─────────┘

In [39]:
print(sum_ids)

321